<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\SEBlueprint.Core\SEBlueprint.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
